"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2@nm9wjdi%*0erp!))$!pjpag*d-vc(n1t#2_rc3e#2q5du)u6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'a.apps.AConfig',
    'rest_framework',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
   
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_db',
        'USER': 'root',
        'PASSWORD': '1234',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True


# R2 配置
R2_ACCESS_KEY_ID = '92da60ad0e5da6ed0900c4cfcf7065ce'
R2_SECRET_ACCESS_KEY = '93957a4e48776dc3c30ddb50ed7babc8db05c695c177915ea24f19c6242859f6'
# 注意：Endpoint 必须是 https://... 开头，且不带 bucket 名字
R2_ENDPOINT_URL = 'https://1667ccbfbaa13fc1546b6f415164f667.r2.cloudflarestorage.com'
R2_BUCKET_NAME = 'post-image' # 你的桶名字
# 👇 重点修改：换成你的自定义域名 
# 注意：千万不要加 https://，只写纯域名，Django 会自动在前面补上 https://
R2_PUBLIC_DOMAIN = 'post.aihikari.xyz'

# 1. 允许的前端域名 (必须精准，不能用 *)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 2. 允许携带 Cookie (关键！配合前端的 withCredentials: true)
CORS_ALLOW_CREDENTIALS = True

# 3. 必须显式关闭 Allow All (因为开启了 Credentials)
CORS_ALLOW_ALL_ORIGINS = False

# 4. CSRF 信任源 (Django 4.0+ 必须配置这个，否则 POST 会报 403)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 5. 允许前端读取的 Cookies
CORS_ExPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
# 允许携带的 Headers
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-csrftoken',
]


# ==========================================
# 将自定义的 R2 配置映射给 django-storages
# ==========================================
AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL

# R2 公开访问域名 (注意：django-storages 的 CUSTOM_DOMAIN 不包含 https://)
AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_DOMAIN.replace('https://', '')

# 关闭查询字符串签名（因为我们用的是公开域名直接访问）
AWS_QUERYSTRING_AUTH = False

# 核心：告诉 Django 默认使用 S3 (R2) 引擎来存储 ImageField 和 FileField 的文件
# ==========================================
# Django 5.x 专属：接管文件存储引擎
# ==========================================
STORAGES = {
    # 覆盖默认的文件存储（处理 ImageField 和 FileField）
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    # 保持静态文件（CSS/JS）依然存在本地
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 👇 新增下面这两行，这是强制兼容 Cloudflare R2 必须加的参数：
AWS_S3_REGION_NAME = 'auto'            # Cloudflare R2 必须指定 region 为 auto 或 us-east-1
AWS_S3_SIGNATURE_VERSION = 's3v4'      # 强制使用 v4 签名，否则会报权限错误


# settings.py 底部

# 1. 必须关闭查询字符串认证，否则 R2 会因为 URL 里的签名参数而报 403 或无法解析
AWS_QUERYSTRING_AUTH = False

# 2. 必须设置自定义域名，且不要带 https://
AWS_S3_CUSTOM_DOMAIN = 'post.aihikari.xyz'

# 3. 确保这个变量被正确映射
AWS_S3_ENDPOINT_URL = 'https://1667ccbfbaa13fc1546b6f415164f667.r2.cloudflarestorage.com'