# Generated by Django 5.2.9 on 2026-01-06 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='原名')),
                ('developer', models.CharField(max_length=100, verbose_name='开发商')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发售日期')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='价格')),
                ('description', models.TextField(verbose_name='剧情简介')),
                ('cover', models.URLField(verbose_name='封面图链接')),
                ('score_avg', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('illustrator', models.CharField(blank=True, max_length=100, verbose_name='插画')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('status', models.CharField(default='连载中', max_length=20, verbose_name='连载状态')),
                ('description', models.TextField(verbose_name='简介')),
                ('cover', models.URLField(verbose_name='封面图链接')),
                ('score_avg', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.TextField(max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='封面图')),
                ('category', models.CharField(default='闲聊', max_length=20, verbose_name='分类')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅读数')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('galgame', 'Galgame'), ('novel', 'Novel'), ('post', 'Post')], max_length=10)),
                ('target_id', models.IntegerField()),
                ('content', models.TextField(verbose_name='评论内容')),
                ('score', models.FloatField(default=0, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('galgame', 'Galgame'), ('novel', 'Novel'), ('post', 'Post')], max_length=10)),
                ('target_id', models.IntegerField()),
                ('status', models.CharField(choices=[('wish', '想玩'), ('playing', '在玩'), ('played', '玩过'), ('fav', '收藏'), ('read', '已读')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.URLField(default='https://naive-ui.oss-cn-beijing.aliyuncs.com/carousel-img/carousel1.jpeg', verbose_name='头像')),
                ('bio', models.TextField(blank=True, default='这个人很懒，什么都没有写~', verbose_name='个性签名')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('exp', models.IntegerField(default=0, verbose_name='经验值')),
                ('is_signed_today', models.BooleanField(default=False, verbose_name='今日是否签到')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='a.tag'),
        ),
        migrations.AddField(
            model_name='galgame',
            name='tags',
            field=models.ManyToManyField(blank=True, to='a.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.userinfo'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.userinfo'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.userinfo', verbose_name='作者'),
        ),
        migrations.AlterUniqueTogether(
            name='usercollection',
            unique_together={('user', 'target_type', 'target_id', 'status')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['target_type', 'target_id'], name='a_review_target__bc1886_idx'),
        ),
    ]
