# Generated by Django 5.2.9 on 2026-01-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_galgame_novel_post_review_tag_usercollection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalgameCg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='CG图片链接')),
                ('galgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgs', to='a.galgame', verbose_name='所属Galgame')),
            ],
        ),
    ]
