# Generated by Django 5.2.9 on 2026-01-08 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_galgamecg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名')),
                ('cv', models.CharField(blank=True, max_length=50, verbose_name='声优(CV)')),
                ('description', models.TextField(verbose_name='角色介绍')),
                ('avatar', models.URLField(verbose_name='立绘图片链接')),
                ('galgame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='a.galgame', verbose_name='所属Galgame')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='a.novel', verbose_name='所属轻小说')),
            ],
        ),
    ]
