# Generated by Django 5.2.9 on 2026-01-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='卷名')),
                ('cover', models.URLField(blank=True, max_length=500, null=True, verbose_name='本卷封面')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发售日')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='a.novel', verbose_name='所属小说')),
            ],
        ),
    ]
