# Generated by Django 5.2.9 on 2026-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_novelvolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='原名'),
        ),
    ]
