# Generated by Django 5.2.9 on 2026-01-09 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_novel_original_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '资讯文章', 'verbose_name_plural': '资讯文章'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '评论/评分'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.userinfo', verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('news', '最新资讯'), ('notice', '站点公告'), ('review', '深度评测'), ('activity', '活动相关')], default='news', max_length=20, verbose_name='资讯分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='正文内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(help_text='用于首页显示的简短介绍', max_length=500, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='target_type',
            field=models.CharField(choices=[('galgame', 'Galgame'), ('novel', 'Novel'), ('post', '资讯/文章')], max_length=10),
        ),
    ]
