# Generated by Django 5.2.9 on 2026-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0007_alter_post_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(default=0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('gal_news', '最新Galgame资讯'), ('gal_review', '热门Galgame点评'), ('novel_news', '最新轻小说资讯'), ('novel_review', '热门轻小说点评')], default='news', max_length=20, verbose_name='资讯分类'),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='target_type',
            field=models.CharField(choices=[('galgame', 'Galgame'), ('novel', 'Novel'), ('post', 'Post')], max_length=10),
        ),
    ]
