# Generated by Django 5.2.9 on 2026-01-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0008_review_score_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('gal_news', 'Galgame资讯'), ('gal_review', 'Galgame点评'), ('novel_news', '轻小说资讯'), ('novel_review', '轻小说点评')], default='news', max_length=20, verbose_name='资讯分类'),
        ),
    ]
