# Generated by Django 5.2.9 on 2026-01-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.URLField(max_length=1000, verbose_name='立绘图片链接'),
        ),
        migrations.AlterField(
            model_name='galgame',
            name='cover',
            field=models.URLField(max_length=1000, verbose_name='封面图链接'),
        ),
        migrations.AlterField(
            model_name='galgamecg',
            name='image_url',
            field=models.URLField(max_length=1000, verbose_name='CG图片链接'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.URLField(max_length=1000, verbose_name='封面图链接'),
        ),
        migrations.AlterField(
            model_name='novelvolume',
            name='cover',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='本卷封面'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='review',
            name='target_type',
            field=models.CharField(choices=[('galgame', 'Galgame'), ('novel', 'Novel'), ('post', 'Post')], max_length=100),
        ),
    ]
