# Generated by Django 5.2.9 on 2026-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0010_alter_character_avatar_alter_galgame_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.URLField(max_length=2000, verbose_name='立绘图片链接'),
        ),
    ]
