# Generated by Django 5.2.9 on 2026-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0011_alter_character_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelvolume',
            name='file_url',
            field=models.URLField(blank=True, max_length=5000, null=True, verbose_name='卷链接'),
        ),
    ]
