# Generated by Django 5.2.9 on 2026-01-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0012_novelvolume_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(help_text='epub.js 的定位字符串', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='a.userinfo')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='a.novelvolume')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'volume')},
            },
        ),
    ]
