# Generated by Django 5.2.9 on 2026-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0013_readingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='歌名')),
                ('singer', models.CharField(max_length=100, verbose_name='歌手')),
                ('album', models.CharField(max_length=100, verbose_name='专辑')),
                ('music_urls', models.URLField(max_length=2000, verbose_name='音频链接')),
                ('duration', models.TimeField(max_length=100, verbose_name='时长')),
            ],
        ),
    ]
