# Generated by Django 5.2.9 on 2026-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0014_musicplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicplayer',
            options={'verbose_name': '音乐库', 'verbose_name_plural': '音乐库'},
        ),
        migrations.AlterField(
            model_name='musicplayer',
            name='album',
            field=models.CharField(blank=True, max_length=100, verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='musicplayer',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='时长'),
        ),
    ]
