# Generated by Django 5.2.9 on 2026-04-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0015_alter_musicplayer_options_alter_musicplayer_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='保密', max_length=20, verbose_name='性别'),
        ),
    ]
