# Generated by Django 5.2.9 on 2026-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0016_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/', verbose_name='封面图'),
        ),
    ]
