# Generated by Django 5.2.9 on 2026-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0017_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='封面图'),
        ),
    ]
